### ISSUE TITLE
does this only work on windows?

### ISSUE THREAD

**Issue by stefangweichinger** [ekutner/kopia-mon#5]
pulled your repo on Fedora 38, installed requirements, added `config.yaml`, getting:

```
python kopia-mon.py
Traceback (most recent call last):
  File "/home/sgw/projects/github/kopia-mon/kopia-mon.py", line 44, in <module>
    repo_info = RepoInfo.create(repo, status.last_run)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgw/projects/github/kopia-mon/repoinfo.py", line 60, in create
    repo.status = kopia.get_repo_status()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgw/projects/github/kopia-mon/kopiaapi.py", line 17, in get_repo_status
    status = self._kopia_command(args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sgw/projects/github/kopia-mon/kopiaapi.py", line 11, in _kopia_command
    with subprocess.Popen(["kopia.exe", *args], stdout=subprocess.PIPE) as proc:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'kopia.exe'
```

**Comment by stefangweichinger** [comment]
Fixed that by editing `kopiaapi.py`.
Now TLS errors .. on my way ;-)

**Comment by stefangweichinger** [comment]
I fixed by googling and trying. No python experience here, but see my change:

```
diff --git a/emailutil.py b/emailutil.py
index 5be7ee2..6c333dd 100644
--- a/emailutil.py
+++ b/emailutil.py
@@ -22,7 +22,8 @@ class Email:
 
         context = ssl.create_default_context()
 
-        with smtplib.SMTP_SSL(self.config["server"]["address"], self.config["server"]["port"], context=context) as server:
+        with smtplib.SMTP(self.config["server"]["address"], self.config["server"]["port"]) as server:
+            server.starttls(context=context)
             server.login(self.config["server"]["user"], self.config["server"]["password"])
             server.sendmail(msg['From'], msg['To'], msg.as_string(), )
             server.quit()
```

config.yaml:

```
email:
  from: noreply@xxx.zz
  to: logs@xxx.zz
  subject: Kopia Backup Report
  subject-error: Kopia Backup Report - HAS ERRORS
  server:
    address: smtp.xxx.zz
    port: 587
    user: sender@xxx.zz
    password: 72dGxxxxxxxxxx
```

**Comment by ekutner** [comment]
Nice. I added a new "transport" parameter to support both SSL and TLS (you're using TLS). Also fixed the ".exe" issue.
Give the latest version a try and let me know if it's working out of the box for you.

**Comment by stefangweichinger** [comment]
@ekutner great, will do. Wouldn't a pull request be the safer way to change things? Just suggesting .. it's your repository ;-)

**Comment by ekutner** [comment]
Probably, but that would have taken me a few more minutes...

**Comment by stefangweichinger** [comment]
might test your changes tmrw. busy as well. thanks
