### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by danmed** [ekutner/kopia-mon#8]
trying to install on Windows 11 with a fresh install of Python. Kopia is in the path and has been confirmed...

```
c:\KOPIA-MON>pip install -r requirements.txt
Collecting dataclasses-json==0.5.7 (from -r requirements.txt (line 1))
  Using cached dataclasses_json-0.5.7-py3-none-any.whl.metadata (22 kB)
Collecting Jinja2==3.1.2 (from -r requirements.txt (line 2))
  Using cached Jinja2-3.1.2-py3-none-any.whl.metadata (3.5 kB)
Collecting python-dateutil==2.8.2 (from -r requirements.txt (line 3))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl.metadata (8.2 kB)
Collecting PyYAML==6.0 (from -r requirements.txt (line 4))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
          self.add_defaults()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\command\sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-32p26efu\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by danmed** [comment]
The solution for me was : 

pip install "cython<3.0.0" && pip install --no-build-isolation pyyaml==6.0

and then 

python setup.py bdist_wheel

**Comment by ekutner** [comment]
As I guess you already figured out, it's a python problem, unrelated to tool itself. pip is unable to build the dependencies. Since I'm using Windows 11 and never had such an issue, I'm guessing there was something wrong with your python installation. Did you install the standard version from python.org and used the default options?

**Comment by danmed** [comment]
from what i've googled it's to do with the release of cython 3.0 recently..

thanks for getting back to me either way.. 

I've been looking for something like this for a while now.. i've not quite figured out how to get it to execute as an after folder action but i've got it running in task scheduler and it executes half an hour after the jobs have run

**Comment by danmed** [comment]
For anyone else looking.... this is my bat file that i finally got to work.. task scheduler is one of those dark arts that you an master one day and then completely forget the next :)

```
cd c:\kopia-mon
C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe c:\KOPIA-MON\kopia-mon.py -c c:\KOPIA-MON\config.yaml
```

**Comment by ekutner** [comment]
You actually don't have to use a batch file.
When you create the task in Windows Task Scheduler you add a "Start program action", set the program to your python.exe (if you are using a venv then use the python.exe file which resides under the venv's "Script" folder), set "kopia-mon.py" as the argument and set "Start in" to the folder where kopia-mon resides. 
This is my setup:
![image](https://github.com/ekutner/kopia-mon/assets/5628151/93060ba1-d287-4b99-9d1d-3e934b4b16c4)

**Comment by Pio55** [comment]
> The solution for me was :
> 
> pip install "cython<3.0.0" && pip install --no-build-isolation pyyaml==6.0
> 
> and then
> 
> python setup.py bdist_wheel

Hello, I had the same problem ("error: subprocess-exited-with-error"), 
maybe someone else can be helped by the solution suggested in this tutorial:
[https://www.youtube.com/watch?v=SpLidAgQuHQ](url)
For me it worked.
In few words, I executed:

**pip install --upgrade setuptools wheel**

then:

**pip cache purge** 

then:

**pip install --no-build-isolation -r requirements.txt**

**Comment by Pio55** [comment]
> You actually don't have to use a batch file. When you create the task in Windows Task Scheduler you add a "Start program action", set the program to your python.exe (if you are using a venv then use the python.exe file which resides under the venv's "Script" folder), set "kopia-mon.py" as the argument and set "Start in" to the folder where kopia-mon resides. This is my setup: ![image](https://private-user-images.githubusercontent.com/5628151/324490378-93060ba1-d287-4b99-9d1d-3e934b4b16c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NDgyNDIsIm5iZiI6MTcyODg0Nzk0MiwicGF0aCI6Ii81NjI4MTUxLzMyNDQ5MDM3OC05MzA2MGJhMS1kMjg3LTRiOTktOWQxZC0zZTkzNGI0YjE2YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTNUMTkzMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA1ZGY2ZmM4MWM5OGExMzg5MWU2YTBkNDI4NjFiYTVhNjE1YjZjMWEyMTg1ZGZjMWQ0OGVlODMxNmNmM2Q2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0BpleoMTMx1rxelqo_uS4grcpMfz_4ntK1CI-Or8SZc)

Hi, I've tried to execute that first from a DOS window (CMD), but it doesn't work for me... here what I got:

![Immagine 2024-10-13 214603](https://github.com/user-attachments/assets/866485a0-4fa2-4b00-a8c8-6fc83edf64bb)

Can you help me?

**Comment by ekutner** [comment]
Well, it says it can't find the config.yaml file... It should be in the same folder as the script itself or specify the location with the -c parameter.
