### ISSUE TITLE
configuration when running kopia in docker

### ISSUE THREAD

**Issue by rmvpaeme** [ekutner/kopia-mon#9]
I have kopia running in Docker on a raspberry pi. I configured the connection to the repository through the GUI. 

When setting this up I get

```
Traceback (most recent call last):
  File "/home/pi/kopia-mon/kopia-mon/kopia-mon.py", line 44, in <module>
    repo_info = RepoInfo.create(repo, status.last_run)
  File "/home/pi/kopia-mon/kopia-mon/repoinfo.py", line 60, in create
    repo.status = kopia.get_repo_status()
  File "/home/pi/kopia-mon/kopia-mon/kopiaapi.py", line 17, in get_repo_status
    status = self._kopia_command(args)
  File "/home/pi/kopia-mon/kopia-mon/kopiaapi.py", line 11, in _kopia_command
    with subprocess.Popen(["kopia", *args], stdout=subprocess.PIPE) as proc:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'kopia'
```

After changing these lines in `kopiaapi.py` to
```
    def _kopia_command(self, args:list[str]):
        args.append(f"--config-file={self._config_file}")
        with subprocess.Popen(["docker", "exec", "Kopia", "kopia", *args], stdout=subprocess.PIPE) as proc:
            res = proc.stdout.read()
            return json.loads(res)
```

I get the error

```
ERROR open repository: repository is not connected. See https://kopia.io/docs/repositories/
Traceback (most recent call last):
  File "/home/pi/kopia-mon/kopia-mon/kopia-mon.py", line 44, in <module>
    repo_info = RepoInfo.create(repo, status.last_run)
  File "/home/pi/kopia-mon/kopia-mon/repoinfo.py", line 60, in create
    repo.status = kopia.get_repo_status()
  File "/home/pi/kopia-mon/kopia-mon/kopiaapi.py", line 17, in get_repo_status
    status = self._kopia_command(args)
  File "/home/pi/kopia-mon/kopia-mon/kopiaapi.py", line 13, in _kopia_command
    return json.loads(res)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ekutner** [comment]
I never tried it with docker so don't know what to expect.
In general, the program should be able to run kopia while providing the --config-file parameter. You should make sure that it's working for you in the console and then it should work for kopia-mon as well. Also, it's a bad idea to change the code like that, better to create a shell script or an alias called kopia that would run the docker command.

**Comment by ekutner** [comment]
I'm not sure why it doesn't find it the kopia program file.
Let's go back to the previous attempt, where you change the code that runs the program. The error you got there is that the repository is not connected. Can you check what happens if you run kopia in the console with the --config-file pointing to the same config file you specified in the kopia-mon config file?

**Comment by rmvpaeme** [comment]
thanks, resolved
